<%
  require_relative "../lib/fizzy"

  config_path = if Fizzy.saas?
    gem_path = Gem::Specification.find_by_name("fizzy-saas").gem_dir
    File.join(gem_path, "config", "database.yml")
  else
    File.join(__dir__, "database.#{Fizzy.db_adapter}.yml")
  end
%>
<%= ERB.new(File.read(config_path)).result %>
